import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';

export default function ApplyJob() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [job, setJob] = useState(null);
  const [mode, setMode] = useState('choose'); // 'choose', 'upload', 'ai-build'
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [generatedCV, setGeneratedCV] = useState(null);
  const [cvFile, setCvFile] = useState(null);
  const [coverLetter, setCoverLetter] = useState('');
  const [userInfo, setUserInfo] = useState({
    name: user?.name || '',
    email: user?.email || '',
    phone: '',
    experience: '',
    education: '',
    skills: '',
    additionalInfo: ''
  });

  const API_BASE = process.env.NODE_ENV === 'production'
  ? 'https://hireflow-hz8e.onrender.com'
  : '/api';

  useEffect(() => {
    axios.get(`${API_BASE}/api/jobs/${id}`).then(r => setJob(r.data)).catch(() => navigate('/jobs'));
  }, [id]);

  const generateCV = async () => {
    if (!userInfo.name || !userInfo.email) {
      toast.error('Please fill in name and email');
      return;
    }
    setAiLoading(true);
    try {
      const { data } = await axios.post(`${API_BASE}/api/ai/generate-cv`, {
        jobTitle: job.title,
        jobDescription: job.description,
        jobRequirements: job.requirements,
        userInfo
      });
      setGeneratedCV(data);
      toast.success('CV generated by AI! Review and submit.');
    } catch (err) {
      toast.error('CV generation failed. Check API key.');
    } finally {
      setAiLoading(false);
    }
  };

  const handleSubmit = async () => {
    if (mode === 'upload' && !cvFile) {
      toast.error('Please upload your CV');
      return;
    }
    if (mode === 'ai-build' && !generatedCV) {
      toast.error('Please generate your CV first');
      return;
    }

    setLoading(true);
    try {
      const formData = new FormData();
      formData.append('coverLetter', coverLetter);

      if (mode === 'upload' && cvFile) {
        formData.append('cv', cvFile);
      } else if (mode === 'ai-build' && generatedCV) {
        formData.append('cvText', generatedCV.cvText);
        formData.append('cvData', JSON.stringify(generatedCV));
      }

      await axios.post(`${API_BASE}/api/applications/${id}`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      toast.success('Application submitted! AI is scoring your CV...');
      navigate('/my-applications');
    } catch (err) {
      toast.error(err.response?.data?.error || 'Failed to submit application');
    } finally {
      setLoading(false);
    }
  };

  if (!job) return <div className="loading-spinner"><div className="spinner" /></div>;

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <div style={styles.header}>
          <h1 style={styles.title}>Apply: {job.title}</h1>
          <p style={styles.sub}>{job.company} · {job.location}</p>
        </div>

        {/* Mode Selection */}
        {mode === 'choose' && (
          <div style={styles.modeGrid}>
            <div style={styles.modeCard} onClick={() => setMode('ai-build')}>
              <span style={styles.modeIcon}>🤖</span>
              <h3 style={styles.modeTitle}>AI CV Builder</h3>
              <p style={styles.modeDesc}>Let AI create a tailored, ATS-optimized CV for this specific job. Takes 30 seconds.</p>
              <div style={styles.modeBadge}>Recommended</div>
            </div>
            <div style={styles.modeCard} onClick={() => setMode('upload')}>
              <span style={styles.modeIcon}>📄</span>
              <h3 style={styles.modeTitle}>Upload Your CV</h3>
              <p style={styles.modeDesc}>Upload your existing CV (PDF, DOC, DOCX, TXT). AI will still score and rank it.</p>
            </div>
          </div>
        )}

        {/* AI CV Builder */}
        {mode === 'ai-build' && (
          <div className="card">
            <div style={styles.formHeader}>
              <h2 style={styles.formTitle}>🤖 AI CV Builder</h2>
              <button onClick={() => setMode('choose')} style={styles.backBtn}>← Change</button>
            </div>
            <p style={styles.formSub}>Fill in your details and AI will craft a tailored CV for "{job.title}" at {job.company}.</p>

            <div style={styles.formGrid}>
              <div className="form-group">
                <label>Full Name *</label>
                <input value={userInfo.name} onChange={e => setUserInfo({...userInfo, name: e.target.value})} placeholder="John Doe" />
              </div>
              <div className="form-group">
                <label>Email *</label>
                <input type="email" value={userInfo.email} onChange={e => setUserInfo({...userInfo, email: e.target.value})} placeholder="you@email.com" />
              </div>
              <div className="form-group">
                <label>Phone</label>
                <input value={userInfo.phone} onChange={e => setUserInfo({...userInfo, phone: e.target.value})} placeholder="+1 234 567 8900" />
              </div>
            </div>

            <div className="form-group">
              <label>Work Experience</label>
              <textarea value={userInfo.experience} onChange={e => setUserInfo({...userInfo, experience: e.target.value})}
                placeholder="E.g. Software Engineer at Google (2020-2023) - Built scalable APIs..." rows={4} />
            </div>
            <div className="form-group">
              <label>Education</label>
              <textarea value={userInfo.education} onChange={e => setUserInfo({...userInfo, education: e.target.value})}
                placeholder="E.g. B.Sc Computer Science, MIT, 2020" rows={3} />
            </div>
            <div className="form-group">
              <label>Key Skills</label>
              <input value={userInfo.skills} onChange={e => setUserInfo({...userInfo, skills: e.target.value})}
                placeholder="Python, React, Machine Learning, Project Management..." />
            </div>
            <div className="form-group">
              <label>Additional Info</label>
              <textarea value={userInfo.additionalInfo} onChange={e => setUserInfo({...userInfo, additionalInfo: e.target.value})}
                placeholder="Certifications, awards, projects, languages..." rows={2} />
            </div>

            {!generatedCV ? (
              <button onClick={generateCV} className="btn-primary" style={styles.generateBtn} disabled={aiLoading}>
                {aiLoading ? '🤖 AI is generating your CV...' : '✨ Generate Tailored CV'}
              </button>
            ) : (
              <div style={styles.cvPreview}>
                <h3 style={styles.cvPreviewTitle}>✅ AI Generated CV Preview</h3>
                <div style={styles.cvBox}>
                  <h2 style={styles.cvName}>{generatedCV.name}</h2>
                  <p style={styles.cvContact}>{generatedCV.email} {generatedCV.phone && `· ${generatedCV.phone}`}</p>
                  <div style={styles.cvSection}>
                    <h4 style={styles.cvSectionTitle}>Professional Summary</h4>
                    <p style={styles.cvText}>{generatedCV.summary}</p>
                  </div>
                  {generatedCV.experience?.length > 0 && (
                    <div style={styles.cvSection}>
                      <h4 style={styles.cvSectionTitle}>Experience</h4>
                      {generatedCV.experience.map((exp, i) => (
                        <div key={i} style={styles.cvExp}>
                          <strong>{exp.role}</strong> at {exp.company}{' '}
                          <span style={{ color: 'var(--text-muted)' }}>({exp.duration})</span>
                          <p style={styles.cvExpDesc}>{exp.description}</p>
                        </div>
                      ))}
                    </div>
                  )}
                  {generatedCV.education?.length > 0 && (
                    <div style={styles.cvSection}>
                      <h4 style={styles.cvSectionTitle}>Education</h4>
                      {generatedCV.education.map((edu, i) => (
                        <p key={i}><strong>{edu.degree}</strong> — {edu.institution} ({edu.year})</p>
                      ))}
                    </div>
                  )}
                  {generatedCV.skills?.length > 0 && (
                    <div style={styles.cvSection}>
                      <h4 style={styles.cvSectionTitle}>Skills</h4>
                      <div style={styles.skills}>
                        {generatedCV.skills.map((s, i) => <span key={i} style={styles.skill}>{s}</span>)}
                      </div>
                    </div>
                  )}
                </div>
                <button onClick={() => setGeneratedCV(null)} style={styles.regenBtn}>🔄 Regenerate</button>
              </div>
            )}
          </div>
        )}

        {/* Upload CV */}
        {mode === 'upload' && (
          <div className="card">
            <div style={styles.formHeader}>
              <h2 style={styles.formTitle}>📄 Upload CV</h2>
              <button onClick={() => setMode('choose')} style={styles.backBtn}>← Change</button>
            </div>
            <div style={styles.dropzone}
              onClick={() => document.getElementById('cv-upload').click()}
              onDragOver={e => e.preventDefault()}
              onDrop={e => { e.preventDefault(); setCvFile(e.dataTransfer.files[0]); }}>
              <input id="cv-upload" type="file" accept=".pdf,.doc,.docx,.txt"
                style={{ display: 'none' }} onChange={e => setCvFile(e.target.files[0])} />
              {cvFile ? (
                <div>
                  <span style={{ fontSize: 32 }}>📎</span>
                  <p style={{ color: 'var(--text)', fontWeight: 600, marginTop: 8 }}>{cvFile.name}</p>
                  <p style={{ color: 'var(--text-muted)', fontSize: 13 }}>Click to change</p>
                </div>
              ) : (
                <div>
                  <span style={{ fontSize: 40 }}>📄</span>
                  <p style={{ color: 'var(--text)', marginTop: 12, fontWeight: 600 }}>Drop your CV here</p>
                  <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 4 }}>PDF, DOC, DOCX, TXT up to 5MB</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Cover Letter + Submit */}
        {mode !== 'choose' && (
          <div className="card" style={{ marginTop: 20 }}>
            <div className="form-group">
              <label>Cover Letter (Optional)</label>
              <textarea value={coverLetter} onChange={e => setCoverLetter(e.target.value)}
                placeholder="Tell the employer why you're the perfect fit for this role..."
                rows={5} />
            </div>
            <div style={styles.submitRow}>
              <p style={{ color: 'var(--text-muted)', fontSize: 13 }}>
                🤖 AI will instantly score and rank your application
              </p>
              <button onClick={handleSubmit} className="btn-primary" style={styles.submitBtn} disabled={loading}>
                {loading ? 'Submitting...' : 'Submit Application →'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

const styles = {
  page: { padding: '40px 24px', minHeight: 'calc(100vh - 64px)' },
  container: { maxWidth: 800, margin: '0 auto' },
  header: { marginBottom: 32 },
  title: { fontFamily: 'Syne, sans-serif', fontSize: 28, fontWeight: 800, color: 'var(--text)' },
  sub: { color: 'var(--text-muted)', marginTop: 6 },
  modeGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 24 },
  modeCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 16,
    padding: 28,
    cursor: 'pointer',
    transition: '0.2s',
    position: 'relative',
    textAlign: 'center',
  },
  modeIcon: { fontSize: 40, display: 'block', marginBottom: 12 },
  modeTitle: { fontFamily: 'Syne, sans-serif', fontSize: 18, fontWeight: 700, color: 'var(--text)', marginBottom: 8 },
  modeDesc: { color: 'var(--text-muted)', fontSize: 14, lineHeight: 1.6 },
  modeBadge: {
    position: 'absolute', top: 16, right: 16,
    background: 'var(--text)', color: 'var(--bg)',
    fontSize: 10, fontWeight: 700, padding: '3px 8px', borderRadius: 100, textTransform: 'uppercase',
  },
  formHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  formTitle: { fontFamily: 'Syne, sans-serif', fontSize: 20, fontWeight: 700, color: 'var(--text)' },
  backBtn: {
    background: 'transparent', color: 'var(--text)', border: '1px solid var(--border)',
    padding: '6px 14px', borderRadius: 8, cursor: 'pointer', fontSize: 13,
  },
  formSub: { color: 'var(--text-muted)', fontSize: 14, marginBottom: 24 },
  formGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 },
  generateBtn: { width: '100%', padding: 14, fontSize: 15, fontFamily: 'Syne, sans-serif', fontWeight: 700 },
  cvPreview: { marginTop: 24 },
  cvPreviewTitle: { fontFamily: 'Syne, sans-serif', fontSize: 16, fontWeight: 700, color: 'var(--text)', marginBottom: 16 },
  cvBox: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    padding: 24,
  },
  cvName: { fontFamily: 'Syne, sans-serif', fontSize: 24, fontWeight: 800, color: 'var(--text)', marginBottom: 4 },
  cvContact: { color: 'var(--text-muted)', fontSize: 13, marginBottom: 20 },
  cvSection: { marginTop: 20, paddingTop: 16, borderTop: '1px solid var(--border)' },
  cvSectionTitle: { color: 'var(--text)', fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 10 },
  cvText: { color: '#30323a', lineHeight: 1.7, fontSize: 14 },
  cvExp: { marginBottom: 12, color: 'var(--text)', fontSize: 14 },
  cvExpDesc: { color: 'var(--text-muted)', marginTop: 4, fontSize: 13 },
  skills: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  skill: {
    background: 'var(--surface2)', color: 'var(--text)',
    padding: '4px 10px', borderRadius: 6, fontSize: 12, fontWeight: 600,
  },
  regenBtn: {
    marginTop: 12,
    background: 'transparent', color: 'var(--text)', border: '1px solid var(--border)',
    padding: '8px 16px', borderRadius: 8, cursor: 'pointer', fontSize: 13,
  },
  dropzone: {
    border: '2px dashed var(--border)',
    borderRadius: 12,
    padding: '48px 24px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: '0.2s',
    marginTop: 16,
  },
  submitRow: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, flexWrap: 'wrap',
  },
  submitBtn: { padding: '12px 28px', fontSize: 15, fontFamily: 'Syne, sans-serif', fontWeight: 700 },
};
